spring.application.name=greenspaces-backend

# Secrets come from this file
spring.config.import=file:src/main/resources/env.properties

# Green space database URL
spring.datasource.url=jdbc:mysql://${DB_URL}

# MySQL credentials
spring.datasource.username=admin
spring.datasource.password=${DB_PASSWORD}

# JPA and Hibernate settings
spring.jpa.show-sql=true