spring.application.name=greenspaces-backend

spring.profiles.active=local

spring.datasource.url=jdbc:mysql://${app.db_url}

# MySQL credentials
spring.datasource.username=admin

# JPA and Hibernate settings
spring.jpa.show-sql=true